Repository sul-dlss/pre-assembly, pull requests merged in 2019-08, with the labels that each got.

#514 Changed SMPL option for content structure and content metadata creation
  app/models/bundle_context.rb
  app/views/bundle_contexts/_new_bc_form.erb
  spec/models/bundle_context_spec.rb
Labels: SDR Fall 2019

#516 add 3d as a valid content type structure
  Gemfile
  Gemfile.lock
  app/lib/pre_assembly/digital_object.rb
  app/models/bundle_context.rb
  app/views/bundle_contexts/_new_bc_form.erb
  spec/models/bundle_context_spec.rb
  spec/test_data/exemplar_templates/TEMPLATE.yaml
Labels: 3d obj

#517 adds 3d support for v3-legacy accessioning
  Gemfile
  Gemfile.lock
  config/projects/TEMPLATE.yaml
  lib/pre_assembly/bundle.rb
Labels: 3d obj

#527 disc report: get error to user for missing container name or manifest
  app/services/discovery_report.rb
  spec/services/discovery_report_spec.rb
  spec/test_data/media_missing/manifest.csv
  spec/test_data/media_missing/media_manifest.csv
  spec/test_data/project_config_files/media_missing.yaml
Labels: SDR Fall 2019, tech debt

#528 Re-accession in pre-assembly
  .rubocop_todo.yml
  Gemfile
  Gemfile.lock
  app/lib/pre_assembly/digital_object.rb
  config/initializers/dor_config.rb
  config/initializers/dor_services_client.rb
  config/settings.yml
  spec/lib/pre_assembly/bundle_spec.rb
  spec/lib/pre_assembly/digital_object_spec.rb
Labels: SDR Fall 2019, reaccessioning
