Repository sul-dlss/pre-assembly, pull requests merged in 2022-06, with the labels that each got.

#941 Allow user to download log for discovery reports; better labels
  app/controllers/job_runs_controller.rb
  app/jobs/preassembly_job.rb
  app/models/job_run.rb
  app/views/job_runs/show.html.erb
  config/routes.rb
  spec/controllers/job_runs_controller_spec.rb
  spec/jobs/preassembly_job_spec.rb
  spec/test_data/input/mock_discovery_report.json
  spec/views/job_runs/show.html.erb_spec.rb
Labels: hold for PO review

#931 make all buttons cardinal-red
  app/assets/stylesheets/application.css
  app/views/batch_contexts/_batch_context.html.erb
Labels: hold for PO review

#956 store errors in the job run and show to the user
  app/jobs/discovery_report_job.rb
  app/jobs/preassembly_job.rb
  app/lib/pre_assembly/batch.rb
  app/models/job_run.rb
  app/services/discovery_report.rb
  app/views/job_runs/show.html.erb
  db/migrate/20220607221157_error_message.rb
  db/schema.rb
  spec/jobs/discovery_report_job_spec.rb
  spec/jobs/preassembly_job_spec.rb
  spec/lib/pre_assembly/batch_spec.rb
  spec/models/job_run_spec.rb
  spec/services/discovery_report_spec.rb
  spec/views/job_runs/show.html.erb_spec.rb
Labels: hold for PO review

#987 batch.rb: improve some method comments
  app/lib/pre_assembly/batch.rb
Labels: tech debt

#995 add a rake task to run analytics on discovery reports
  lib/tasks/reports.rake
Labels: hold for PO review

#994 add info to progress log file for discovery reports
  app/services/discovery_report.rb
  spec/features/discovery_report/build_manifest_image_spec.rb
  spec/features/discovery_report/file_manifest_book_spec.rb
  spec/test_data/input/mock_discovery_report.json
Labels: hold for PO review

#1003 remove unused assembly-image gem
  Gemfile
  Gemfile.lock
Labels: tech debt, SDR improvements

#1004 remove reference to Assembly::ObjectFileable
  app/lib/pre_assembly/object_file.rb
Labels: tech debt, SDR improvements

#1008 define DigitalObject#==, let it be used implicitly in test comparisons
  spec/lib/pre_assembly/batch_spec.rb
  spec/spec_helper.rb
Labels: refactor, tech debt
